language: php

php:
    - 7.0
    - 7.1

sudo: false

before_install:
    - if [[ $TRAVIS_PHP_VERSION != 7.1 ]] ; then phpenv config-rm xdebug.ini; fi

install: 
    - composer install --no-dev
    - tar -cvf content.tar ../content
    - xz -z9 content.tar
    # - travis_retry composer install --no-interaction --prefer-dist --no-suggest

# script: vendor/bin/phpunit --verbose

after_success:
    - curl -T notadd.tar.xz http://v0.api.upyun.com/notadd/download/module/content-master.tar.xz -u "$UPYUN" -v

notifications:
    webhooks:
        - https://hook.bearychat.com/=bwA22/travis/52fa443470377f35e5a3d068b8d2d5ca
        - https://hook.bearychat.com/=bwA7K/travis/790ae0f9fac441dc975a92cb735622fe
