name: 文章CMS
identification: notadd/content
description: 'Notadd 内容管理模块'
author:
    - Notadd
    - notadd@ibenchu.com
version: 2.0.0
assets:
    administration:
        notadd/content:
            permissions: ''
            scripts: assets/content/administration/js/module.min.js
            stylesheets: assets/content/administration/css/module.min.css
csrf:
    - 'api/article*'
    - 'api/category*'
    - 'api/content*'
    - 'api/page*'
entry: '/content'
menus:
    content:
        icon: ios-book
        permission:
        path: '/content'
        text: CMS
        children:
            -
                children:
                    -
                        path: /content/article
                        text: 全部文章
                    -
                        path: /content/article/category
                        text: 分类管理
                    -
                        path: /content/article/information
                        text: 信息管理
                    -
                        path: /content/article/recycle
                        text: 回收站
                icon: plus
                text: 文章管理
            -
                children:
                    -
                        path: /content/page
                        text: 全部页面
                    -
                        path: /content/page/category
                        text: 分类管理
                icon: plus
                text: 页面管理
            -
                children:
                    -
                        path: /content/component
                        text: SEO 配置
                icon: plus
                text: 模块管理
migrations:
    - databases/migrations
permissions:
    -
        description: 内容管理权限。
        groups:
            -
                description: 内容管理权限定义。
                identification: content
                name: 内容管理权限
        identification: content
        name: 内容管理
publishes:
    assets/content/administration: resources/mixes/administration/dist/assets/content/administration
    assets/content/foreground: resources/mixes/foreground/dist/assets/content/foreground
settings:
    content.seo.article.description: ''
    content.seo.article.keyword: ''
    content.seo.article.title: ''
    content.seo.category.description: ''
    content.seo.category.keyword: ''
    content.seo.category.title: ''
    content.seo.page.description: ''
    content.seo.page.keyword: ''
    content.seo.page.title: ''
